version: "3.8"

services:
  pibaque:
    image: docker pull ghcr.io/mathiuscp/ci-cd-examen-pibaque/pibaque:1.0.5
    build: .
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pibaque.entrypoints=http"
        - "traefik.http.routers.pibaque.rule=Host(`pibaque.byronrm.com`)"
        - "traefik.http.middlewares.pibaque-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.pibaque.middlewares=pibaque-https-redirect"
        - "traefik.http.routers.pibaque-secure.entrypoints=https"
        - "traefik.http.routers.pibaque-secure.rule=Host(`pibaque.byronrm.com`)"
        - "traefik.http.routers.pibaque-secure.tls=true"
        - "traefik.http.routers.pibaque-secure.tls.certresolver=http"
        - "traefik.http.routers.pibaque-secure.service=pibaque"
        - "traefik.http.services.pibaque.loadbalancer.server.port=1001"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true